services:
  web:
    image: node:22
    working_dir: /app
    ports:
      - "5173:5173"
    command: "npm run dev -- --host"
    volumes:
      - ./client:/app
  backend:
    image: denoland/deno:1.42.4
    working_dir: /app
    ports:
      - "8080:8080"
    command: "deno run --allow-net --watch ./src/main.ts"
    volumes:
      - ./server:/app
