# fly.toml app configuration file generated for acroserver on 2023-10-22T14:56:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "acroserver"
primary_region = "yyz"

[build]

[env]
  PORT = "8080"

[processes]
  app = "run --allow-net ./src/main.ts"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
